"""add edinet inventory tables

Revision ID: 2290170f9497
Revises: 2183f9cf2396
Create Date: 2026-09-06 07:42:13.563978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2290170f9497'
down_revision: Union[str, Sequence[str], None] = '2183f9cf2396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edinet_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('edinet_code', sa.String(length=255), nullable=True),
    sa.Column('sec_code', sa.String(length=255), nullable=True),
    sa.Column('filer_name', sa.String(length=255), nullable=True),
    sa.Column('ordinance_code', sa.String(length=255), nullable=True),
    sa.Column('form_code', sa.String(length=255), nullable=True),
    sa.Column('doc_type_code', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('submit_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_description', sa.Text(), nullable=True),
    sa.Column('parent_doc_id', sa.String(length=255), nullable=True),
    sa.Column('withdrawal_status', sa.String(length=255), nullable=True),
    sa.Column('doc_info_edit_status', sa.String(length=255), nullable=True),
    sa.Column('disclosure_status', sa.String(length=255), nullable=True),
    sa.Column('xbrl_flag', sa.String(length=255), nullable=True),
    sa.Column('pdf_flag', sa.String(length=255), nullable=True),
    sa.Column('csv_flag', sa.String(length=255), nullable=True),
    sa.Column('legal_status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edinet_documents_doc_id'), 'edinet_documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_edinet_documents_doc_type_code'), 'edinet_documents', ['doc_type_code'], unique=False)
    op.create_index(op.f('ix_edinet_documents_sec_code'), 'edinet_documents', ['sec_code'], unique=False)
    op.create_index(op.f('ix_edinet_documents_submit_date_time'), 'edinet_documents', ['submit_date_time'], unique=False)
    op.create_index(op.f('ix_edinet_documents_target_date'), 'edinet_documents', ['target_date'], unique=False)
    op.create_table('edinet_inventory_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('listed_match_count', sa.Integer(), nullable=False),
    sa.Column('csv_flag_count', sa.Integer(), nullable=False),
    sa.Column('listed_sec_code_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edinet_inventory_runs_target_date'), 'edinet_inventory_runs', ['target_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edinet_inventory_runs_target_date'), table_name='edinet_inventory_runs')
    op.drop_table('edinet_inventory_runs')
    op.drop_index(op.f('ix_edinet_documents_target_date'), table_name='edinet_documents')
    op.drop_index(op.f('ix_edinet_documents_submit_date_time'), table_name='edinet_documents')
    op.drop_index(op.f('ix_edinet_documents_sec_code'), table_name='edinet_documents')
    op.drop_index(op.f('ix_edinet_documents_doc_type_code'), table_name='edinet_documents')
    op.drop_index(op.f('ix_edinet_documents_doc_id'), table_name='edinet_documents')
    op.drop_table('edinet_documents')
    # ### end Alembic commands ###
